#!/bin/bash

# allow all docker hosts to our X server
xhost +local:docker

# start our container and a terminal
docker run \
       -it \
       --rm \
      -v /tmp/.X11-unix:/tmp/.X11-unix:rw \
      -e DISPLAY=unix${DISPLAY} \
      --device /dev/snd \
      --device /dev/net/tun \
      --cap-add=NET_ADMIN \
      --name freerdp-openconnect \
      <IMAGE_ID HERE>
